#!/usr/bin/env ruby

require 'date'
require 'pathname'

TOOLS = Pathname.new File.dirname __FILE__
SRC   = TOOLS + "../source"
NOV   = TOOLS + "../novel"
NOVL  = SRC + "novel-list.txt"
IDS   = File.read(NOVL).lines.map(&:chomp).sort
day4id = Date.today

begin
  id = `date -d @'#{day4id.to_time.to_i}' +%Y-%m-%d`.chomp
  day4id = day4id.succ
end until IDS.last < "#{id}.rst"

BODYF = SRC + "#{id}.rst"
OUTF  = NOV + "#{id}.rst"

`touch #{BODYF}`
`touch #{OUTF}`
`git add #{BODYF}`
`git add #{OUTF}`
`echo #{id}.rst >> #{NOVL}`
